version: '3.3'

services:
    wp:
        build: .
        ports:
            - 80:80
        volumes:
            - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
            - ./project:/var/www/html
        depends_on:
            - db
        links:
            - db
        environment:
            DB_NAME: wordpress
            DB_USER: root
            DB_PASSWORD: 123456
            DB_HOST: db
            WP_DEBUG: 1
            WP_DEBUG_LOG: 1
            LIVE_URL: https://production.site
            DEV_URL: http://development.sit

    db:
        image: mysql:8.0
        ports:
            - 3306:3306
        command: [
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: 123456

volumes: 
    db_data:
