version: "3.6"

services:
    db:
        container_name: docker-wp_db
        image: mysql:8
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: wordpress
        command: [
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]

    wp:
        container_name: docker-wp_wp
        build: .
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
            - ./project:/var/www/html
        depends_on:
            - db
        environment:
            DB_NAME: wordpress
            DB_USER: root
            DB_PASSWORD: 123456
            DB_HOST: db
            DB_PREFIX: wp_
            WP_ADMIN: admin
            WP_ADMIN_EMAIL: admin@example.com
            WP_ADMIN_PASSWORD: 123456
            WP_TITLE: Test
            LIVE_URL: https://production.site
            DEV_URL: http://development.local

volumes: 
    db_data:
